# Generated by Django 4.0.2 on 2022-11-30 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_newtweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newtweet',
            old_name='content',
            new_name='caption',
        ),
    ]
