# Generated by Django 4.0.2 on 2022-12-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_content_newtweet_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newtweet',
            old_name='author',
            new_name='user',
        ),
    ]
