# Generated by Django 4.1.7 on 2023-04-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_newtweet_options_remove_profile_id_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='user',
        ),
    ]
