# Generated by Django 4.1.7 on 2023-04-11 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_remove_profile_bio_remove_profile_follows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='fans', to=settings.AUTH_USER_MODEL),
        ),
    ]
