# Generated by Django 4.1.7 on 2023-04-12 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_user_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='follower',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='followers',
            name='follows',
        ),
        migrations.AddField(
            model_name='followers',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='fan', to='network.followers'),
        ),
    ]
