# Generated by Django 4.1.7 on 2023-04-12 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_alter_followers_follower_remove_followers_follows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='fan', to=settings.AUTH_USER_MODEL),
        ),
    ]
