# Generated by Django 4.1.7 on 2023-04-17 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_alter_contact_follow_from_alter_contact_follow_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='follows',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
