# Generated by Django 4.1.7 on 2023-04-20 19:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_remove_profile_follows_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtweet',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
