# Generated by Django 4.1.7 on 2023-04-21 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_newtweet_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='follows_before',
        ),
        migrations.RemoveField(
            model_name='followers',
            name='user_before',
        ),
        migrations.RemoveField(
            model_name='likespost',
            name='username',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='following',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='post',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='user',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Followers',
        ),
        migrations.DeleteModel(
            name='LikesPost',
        ),
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
